### ISSUE TITLE
Initial Figma Audit of all HfLA teams

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#109]
### Overview
We need to audit each project's figma to determine how they are organized and what components/features they have so that when we publish our guidance on design systems we can see how those projects are improved over time.

#### Part of Epic: Audits of HfLA Project Figmas to establish data points
We will be performing a series of audits #110 to establish baselines to measure the effectiveness of our teams activities. This is the first of several.

### Action Items
- [x] Build a spreadsheet with
  - [x] Lists of projects
  - [x] Project contacts
  - [x] components/features we are assessing
     - [x] Colors
     - [x] Typography
     - [x] Components
     - [x] Icons/Grids
     - [x] Shadows/Spacing
     - [x] Code Library
- [ ] Add notes in the comments about progress auditing teams figmas and other sources.

### Resources/Instructions
[Audit Document](https://docs.google.com/spreadsheets/d/1BlfLbyPUyIJ-xE4wftO_-UXNjtOIsn4NMJ7WTiIXNyI/edit#gid=0)

**Comment by Hanastevenson** [comment]
@ExperimentsInHonesty A [Google Document](https://docs.google.com/spreadsheets/d/1BlfLbyPUyIJ-xE4wftO_-UXNjtOIsn4NMJ7WTiIXNyI/edit#gid=0) has been created. Please can you add in the details as discussed

**Comment by nasimbiglari** [comment]
Access-the-datas guide is restricted. Is it possible to get access? link to the guide: https://docs.google.com/presentation/d/1Fuc_OrS5Jb2ocpDkJJ3bFwdLfYjkUBpwiVKQ1tpePok/edit#slide=id.p

**Comment by ExperimentsInHonesty** [comment]
@nasimbiglari I have made the document for Access the data viewable by anyone [Access the Data 
Brand and Style Guide](https://docs.google.com/presentation/d/1Fuc_OrS5Jb2ocpDkJJ3bFwdLfYjkUBpwiVKQ1tpePok/edit#slide=id.p)

**Comment by ExperimentsInHonesty** [comment]
@Hanastevenson I have edited the spreadsheet to update all the people on the teams.  I knew who most of the teams have as current leadership, and was only unable to identify the designers on two projects, although I was able to indicate current PMs
- Home Unite Us
- Design Systems

I also updated the top of this issue
And made a new issue as the epic in order to identify the other audits that will need to be conducted.
I also added a new feature label that you can add to all epic issues.

**Comment by ExperimentsInHonesty** [comment]
@Hanastevenson I realized there was one project missing.  I found their figma file but dont know who the design lead is
- Civic Tech Jobs

**Comment by kelenelee** [comment]
- [ ] #120
