### ISSUE TITLE
Epic: Audits of HfLA Project Figmas to establish data points

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/design-systems#110]
### Overview
REPLACE THIS TEXT -Text here that clearly states the purpose of this issue in 2 sentences or less.

### Details
We will be performing the following audits (each will have its own issue)
- [ ] [Audit of the current "as is" state ](https://github.com/hackforla/design-systems/issues/109)
  - [ ] Due: Now
  - [ ] Value of Audit: To identify if the process of interacting with the teams (even them hearing about the project) and/or explaining the Design Systems project will result in them making improvements on their own.
- [ ] Audit of the projects before interviews
  - [ ] Due: before the interviews start if they start more than 1 month after the first audit,
  - [ ] Value of Audit: establishing an "as is" state before the interviews to determine the baseline for the the effects of interviewing.
- [ ] Audit of the projects before publication
  - [ ] Due: immediately before publication of guidance
  - [ ] Value of Audit: establishing an "as is" state before the publication to determine the baseline for how people respond to publication.
- [ ] Audit of the projects after publication
  - [ ] Due: 1 month after publication
  - [ ] Value of Audit: establishing a data point after initial launch to determine benefits of new materials on projects and speed of adoption.
- [ ] Audit of the projects after publication + 6months
  - [ ] Due: 6 months after publication
  - [ ] Value of Audit: establishing a data point after a reasonable time has passed to determine benefits of materials on projects (new and old) and speed of adoption.
- [ ] Audit of the projects after publication + 1 year
  - [ ] Due: 12 months after publication
  - [ ] Value of Audit: establishing a data point after a significant time has passed to determine benefits of materials on projects (new and old) and speed of adoption.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by allthatyazz** [comment]
- On 2022/3/14,  during stakeholder meeting ( see the [agenda](https://github.com/hackforla/design-systems/issues/89#issuecomment-1066922878)) a new spreadsheet has been created to update the older Figma Audit. 
 - On 2022/3/18, Yas (PM) has updated the file and added fa ew new columns to the audit that could be relevant to the Figma Foundations tutorial. 

### Resources
 [New Spreadsheet](https://docs.google.com/spreadsheets/d/1OuA3eDW0qfjgo-kywpxUFgVHeh3pyXj43b1wr0iXLBE/edit?usp=sharing)

**Comment by allthatyazz** [comment]
- On 6/16, @kangina-tech and I met and discussed the need to enhance the [spreadsheet audit](https://docs.google.com/spreadsheets/d/1OuA3eDW0qfjgo-kywpxUFgVHeh3pyXj43b1wr0iXLBE/edit?usp=sharing) and expand it into a more visual format (similar to what I started in my [Sandbox](https://www.figma.com/file/5NacfOm45QlrWgr6wWEg4k/Design-System-Template-for-HfLA?node-id=2%3A31)). For now, we gather the data and the next step would be analyzing what each team has done and mapping the insights from the user interviews to the relevant projects.
