### ISSUE TITLE
Stakeholder and PM Agenda Week of the 27th September 

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#117]
### Overview
A weekly meeting to discuss project board, Issues, product management techniques.

### Action Items

- [x] [Review Product Roadmap](https://docs.google.com/spreadsheets/d/1sClBkxwUtvLNAM0Mpn8ztuzy-ypdVoEFYzBvvuvUwZQ/edit#gid=0)
- [x] Arrange meeting for creating a new Figma file #114 
- [ ] Update on adding Design Systems to HfLA website #78 
- [ ] Review the Inactive members on the team #113 
- [x] Review Epics

**Comment by ExperimentsInHonesty** [comment]
@Hanastevenson please add to agenda
Tell Guides team which issues cover the guides your team is making.  If there is a label that ties them all together we can start there.

**Comment by Hanastevenson** [comment]
@ExperimentsInHonesty Reminder. Action point 2. #114 
Ryan _"I can do anytime Monday 9/27 or Tuesday 9/28 after 4:00 pm PT."

**Comment by Hanastevenson** [comment]
> @Hanastevenson please add to agenda
> Tell Guides team which issues cover the guides your team is making. If there is a label that ties them all together we can start there.
> Are you sure you are not doing a typograph guide? [hackforla/guides#19](https://github.com/hackforla/guides/issues/19)

Here is the link to Issues with the Guide label.
https://github.com/hackforla/design-systems/labels/P%20-%20Feature%20Draft%20Guide

**Comment by Hanastevenson** [comment]
@Hanastevenson to speak Matthew from HfLA website team on Automating update issue reminders.

**Comment by Hanastevenson** [comment]
@ExperimentsInHonesty Balot Nav survey, how to keep the data straight. Also, the neighbor council competitor analysis.

**Comment by ExperimentsInHonesty** [comment]
I took most of the week off of my meetings.  Can you touch base with Ryan again and find out when he is available
https://github.com/hackforla/design-systems/issues/117#issuecomment-928166765

**Comment by ExperimentsInHonesty** [comment]
Confirming that I should transfer this issue to your repo?
https://github.com/hackforla/UI-UX/issues/48

**Comment by Hanastevenson** [comment]
Yes.
