### ISSUE TITLE
Create Framework for HfLA Design System Checklist

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#154]
### Overview
Build out a framework for what a design system checklist would contain. This will be used to help measure the status of each of HfLA's project's design systems.

**This work will be presented in the next design meeting on 10/19**, if you are not able to make the meeting, no worries, but please have work created in the figjam.

### Action Items
- [x] Conduct additional research (articles, videos, other design systems, etc.) to find content that will help to build out a HfLA design system checklist
- [x] Conduct research on how the effectiveness of a design system can be measured
- [x] Use findings from research to brainstorm and create your own general framework of a checklist for HfLA's Design System 
- [x] Add framework to [figjam file](https://www.figma.com/file/mmvbxZ6lctjQneEeqTjC8O/Design-Check-list?node-id=0%3A1)

### Resources/Instructions
[Figjam document for brainstorming/framework](https://www.figma.com/file/mmvbxZ6lctjQneEeqTjC8O/Design-Check-list?node-id=0%3A1)
