### ISSUE TITLE
EPIC - Add the Design Systems guide to the Toolkit page 

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#21]
### Dependency

Check to see if HackforLA toolkit has relaunched

### Overview
For our MVP solution we need to understand the new ToolKit page on the HfLA website so that we can create the correct outcome.

### Action Items

- [ ] What MVP Design System content are we including on Toolkit page
- [ ]  Find out when the new Toolkit UI design is scheduled to be completed
- [ ] Explore how we will display our Design System content on the new Toolkit page
- [ ] Find out when the new Toolkit design is scheduled to be live on the HfLA site
