### ISSUE TITLE
Agenda for week of 6th December 2021

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#238]
### Overview

This issue tracks the agenda for the design systems meetings and weekly roll call for projects.

As discussed in a previous Team meeting [ticket:](https://github.com/hackforla/design-systems/issues/219) The below is what is needed for before the end of the year.

- [x] Recruitment Survey out (Deadline 16th Nov)
- [x] Google Drive organised
- [x] Interview scripts all completed
- [ ] Wiki and Figma Insights document combined (Deadline 30th Nov)
- [ ] Confirm at least 13 interviews.
- [ ] Research and UX/UI sections to be updated in the Wiki 
- [ ] Foundation draft complete
- [ ] Wiki template complete

### Action Items

- [x] Please check in on the [Roll Call Spreadsheet](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=0)
- [x] Research Update
- [x] UX/UI Update
- [ ] As a team please discuss what pages need to be designed for an insights document as Anh will be working on it this week.

These tickets need to be completed by the **next Monday meeting** (13th December)

**Research team** @nasimbiglari 

- [ ] Update the Research section for the Wiki https://github.com/hackforla/design-systems/issues/236
- [x] Developers interview script https://github.com/hackforla/design-systems/issues/167
- [x] Post interview guide https://github.com/hackforla/design-systems/issues/177
- [x] PMs Interview script  https://github.com/hackforla/design-systems/issues/165
- [x] Create interview questions & script for designers https://github.com/hackforla/design-systems/issues/36
- [x] Research interview questions & script for PM's https://github.com/hackforla/design-systems/issues/35

**UX/UI Team** @rcurtis2 

- [ ] UX/UI Wiki https://github.com/hackforla/design-systems/issues/136
- [ ] @ahoang94 to add content to the ticket and create first draft -Create a Design Systems branded template https://github.com/hackforla/design-systems/issues/234
- [x] Present the compiled findings/insights and data from the Figma and wiki audit
- [ ] Each member of the team to create a draft foundation template for the Figma file and prepare to present at the next Monday meeting.

**Comment by JeannyRen** [comment]
Design team progress
- Draft presentation on figma and wiki audits, will be presented to PM tomorrow 1 on 1. The finalized presentation will go to the stakeholder.
- Next week the design team will create a foundation template for the Figma files.

**Comment by Hanastevenson** [comment]
PM joined the Research meeting and discussed the above tickets.
PM had a 1-2-1 with the UX/UI lead to discuss blockers and this week's agenda.

Team blocker - _The overall team is wondering whether the Monday evening meetings will proceed during the last weeks of December. Presumably not since so many people will be absent during these two holiday weeks._

Meeting times for the last meeting of 2021 have been posted in the Design Systems Slack channel.
