### ISSUE TITLE
DS: UX/UI Team Meetings (2022)

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#264]
### Overview
This issue tracks the agenda for the Design team's weekly meetings:

#### Template
```
[DATE] Agenda and Notes

### Prework
- [ ] Add prework here

### Roll Call

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)

 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bernard](https://github.com/hackforla/UI-UX/issues/88)
       - [ ]  [Wataru Inoue](https://github.com/hackforla/UI-UX/issues/189)
       - [ ] [Ryan] (https://github.com/hackforla/UI-UX/issues/67)

#### New Items
- [ ] 
#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda
```

### 2021 Weekly Agendas:
[Issues from 2021](https://github.com/hackforla/design-systems/issues/95)

**Comment by Hanastevenson** [comment]
Tuesday 18th January Agenda and Notes

### Prework
- [ ] PM and Lead meeting

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/internship/projects/1#column-15516595)

 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bernard](https://github.com/hackforla/UI-UX/issues/88)
       - [ ]  [Wataru Inoue](https://github.com/hackforla/UI-UX/issues/189)
       - [ ] [Ryan] (https://github.com/hackforla/UI-UX/issues/67)
       - [ ] [Alena](https://github.com/hackforla/UI-UX/issues/194)
- [ ] finish adding labels to the issue that are still missing them 



#### New Items
#### Task items from Team meeting to review
- [ ] 

- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by Hanastevenson** [comment]
Tuesday 25th Agenda and Notes

### Prework
- [ ] PM and Lead to create the first UX/UI work

### Roll Call

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)

 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bernard](https://github.com/hackforla/UI-UX/issues/88)
       - [ ]  [Wataru Inoue](https://github.com/hackforla/UI-UX/issues/189)
       - [ ] [Ryan] (https://github.com/hackforla/UI-UX/issues/67)

#### New Items
- [ ] 
#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by Hanastevenson** [comment]
1st Feb Agenda and Notes

### Prework
- [ ] Add prework here

### Roll Call

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)

 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bernard](https://github.com/hackforla/UI-UX/issues/88)
       - [ ]  [Wataru Inoue](https://github.com/hackforla/UI-UX/issues/189)
       - [ ] [Ryan] (https://github.com/hackforla/UI-UX/issues/67)

#### New Items

- [ ]  Discuss new joiner thoughts on the guide
- [ ]  Go through Figma Foundation
- [ ]  Go through the Universal design system

#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by Hanastevenson** [comment]
[DATE] Agenda and Notes

### Prework
- [ ] Add prework here

### Roll Call

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)

 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bernard](https://github.com/hackforla/UI-UX/issues/88)
       - [ ]  [Wataru Inoue](https://github.com/hackforla/UI-UX/issues/189)
       - [ ] [Ryan] (https://github.com/hackforla/UI-UX/issues/67)

#### New Items
- [ ] 
#### Task items from Team meeting to review
- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**3/1/2022 Agenda and Notes**

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)

 - [ ] Accountability and Support Check.
    - [ ] Review assignments 
       - [ ]  [Wataru Inoue](https://github.com/hackforla/UI-UX/issues/189)

#### New Items

- [ ]  Discuss recruiting new joiners
- [ ]  Go through Figma Foundation

#### Task items from Team meeting to review


### FYI

### Notes from meeting
- 

### New Task Items



#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**3/8/2022 Agenda and Notes**

#### Prework
 - [ ] Read the notes from previous week for context

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] review any issues that are in the [In Progress Column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments :  Tammy and Nana Yaa explain their progress with their first tickets
   
#### New Items
- [ ]  Hana (previous PM) helps the UX team understand the Figma Foundation initiative better
- [ ]  Review  Wataru's presentation with the new joiners
- [ ]  Discuss Cherilyin (from the Internship project) who is sent by Bonnie to test our guide (opportunity for usability study)
- [ ] Discuss the steps needed for turning Wataru's tutorial into a test-ready MVP for the usability study


#### Task items from Team meeting to review


### FYI

### Notes from meeting
- 
### New Task Items
 - 

#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**3/15/2022 Agenda and Notes**

#### Prework
 

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] review any issues that are in the [In Progress Column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments :  Tammy and Nana Yaa explain their progress with their first tickets
   
#### New Items
- [ ]  Hana (previous PM) helps the UX team understand the Figma Foundation initiative better
- [ ]  Review  Wataru's presentation with the new joiners
- [ ]  Discuss Cherilyin (from the Internship project) who is sent by Bonnie to test our guide (opportunity for usability study)
- [ ] Discuss the steps needed for turning Wataru's tutorial into a test-ready MVP for the usability study


#### Task items from Team meeting to review


### FYI

### Notes from meeting


### New Task Items
 - 

#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**3/22/2022 Agenda and Notes**

#### Prework
  - [ ] Add items to the Agenda after stakeholder meeting and all-team meeting here

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] review any issues that are in the [In Progress Column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments :  Personas and Figma Foundations 
   
#### New Items
- [ ]  Cover page for Figma Foundations
- [ ]  
- [ ] 


#### Task items from Team meeting to review


### FYI


### New Task Items
 
#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**3/29/2022 Agenda and Notes**

#### Prework
  - [ ] Inform the Design team so they can use the agenda and add their own items to it. 

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] review any issues that are in the [In Progress Column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments :  Figma Foundations 
   
#### New Items
- [ ]. 



#### Task items from Team meeting to review


### FYI

### Notes from the meeting
  - Attendees: 
  - Discussed: 
  - Decided: 



### New Task Items
 
#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**4/5/2022 Agenda and Notes**

#### Prework
  - [ ] Prepare the agenda

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] review any issues that are in the [In Progress Column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments :  Figma Foundations 
   
#### New Items
 - [ ] Going through diffrent sections of Figma Foundations


#### Task items from Team meeting to review


### FYI

### Notes from the meeting
  - Attendees: Wataru, Tammy, Sandra
  - Discussed: 
  - Decided: 






### New Task Items
 
#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**4/11/2022 Agenda and Notes**

#### Prework
  - [x] Prepare the agenda

#### Recurring items: Happens on the UX/UI meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] review any issues that are in the [In Progress Column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments :  Figma Foundations 
   
#### New Items
 - [ ] Going through diffrent sections of Figma Foundations


#### Task items from Team meeting to review


### FYI

### Notes from the meeting
  - Attendees: 
  - Progress: 
  - Discussed: 
  - Decided: 
 






### New Task Items
 
#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**Tuesday 4/19 Agenda and Notes **

### Prework

### FYI
This is a joint session with the Research and Design teams in lieu of All Team meeting. 

### Roll Call

Please check in on the [Roll Call Spreadsheet](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=0)


#### Recurring items: Happens on the PM Monday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/design-systems/projects/1#column-15412961)
 - [ ]  review any issues that are in the [In Progress column](https://github.com/hackforla/design-systems/projects/1#column-15133576)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each team
       - [ ] [Research](https://github.com/hackforla/design-systems/projects/1?card_filter_query=label%3A%22role%3A+research%22)
       - [ ] [UX/UI](https://github.com/hackforla/design-systems/projects/1?card_filter_query=label%3A%22role%3A+ui%22+label%3A%22role%3A+ux%22) 
       


#### New Items
 - [ ] Design Workshop Day: Research and design teams would go over the first usability study and present their observations.
    - [ ] Provide the general overview of the first test.
    - [ ] Address how we can improve the design.
    - [ ] Discuss if we need another template for note-taking.
 - [ ] Discuss the templates for usability #396 
 - [ ] Discuss the timeline for the 2nd round of usability studies
 - [ ] (if we have time) Go over the GitHub's project board with the team to review the recent changes
 
#### Task items from Team meeting to review


### Notes from meeting
  - Attendees: 
  - Progress: 
  - Discussion:  
  - Decided: 
    

### New Task Items

#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**Tuesday 4/26  Meeting Notes **
 - Attendees: Wataru, John, Tammy, Yas
 - Progress: 
    - Team worked on minor/quick fixes after the usability test with Participant 1 or P1. 
 - Discussion: 
   - We discussed the issues related to the next section in Figma Foundations which is going to be about "Creating a Start Page". We discussed the distinction between "MVP" and "Ideal" templates that are not going to work for every section like "Start Page" because "ideal" could mean different things for different projects. We discussed the possibility of merging the templates into one page.
   - We discussed some other solutions for the other pages.
 - Team decided to keep the design consistent for the second participant or participant B.

**Comment by allthatyazz** [comment]
**Tuesday 5/3  Meeting Notes**

 - Attendees: Wataru, John, Tammy, Yas
 - Progress: 
    - Team conducted the 2nd usability study in the past week and during Monday's all-hands meeting, the whole team collaborated on a [FigJam file](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=0%3A1) to consolidate the data after two usability tests. Each team member put down their sticky notes on the FigJam. Sandra's notes were turned into stickies by John, Yas, and Dongchen. 
    - Research team lead @hdchangie  provided a preliminary list of [recommendations](https://docs.google.com/document/d/1zJvP6aoOHSfICTW01w1o1JVcSxE7uJqC/edit?usp=sharing&ouid=105768861281432074552&rtpof=true&sd=true) to the Design team to improve major and minor issues related to the design. The design team used this document during the meeting to discuss areas that needed improvement.  
 - Discussion: 
   - We discussed the idea of the checklist and ways to make it "clear" for the users about "requirements/ mandatory changes" vs "optional changes".
   - We discussed ways to improve the "Start here" page such as 
      - Have 1 frame on the Start page instead of multiple frames. In a way, the team is moving from "having a slide deck" to a sort of  "building a landing page" mentality. 
      - Rework the "How to use" wording. Alternatives discussed "What to expect" or "How to Navigate FF". 
      - Replace screenshots with illustrations. 
      - Replace the list of steps (text) with graphics or columns of a more visually-appealing nature.  
 - Team decided that each designer would work on their version of the pages to present them during the next all-hands meeting. So, the researchers can vote on the design as well.

**Comment by sandraberjan** [comment]
6/1 Wednesday Design Team Meeting
Attendees: Wataru, Tammy, Sandra

Discussion
-Sandra’s slide deck on design decisions; Wataru “an ever-growing QA document for design”; placed it on back burner for now due to more pressing matters
-Most recent design(s) and research recommendations to make sure we're all up to speed and on the same page
-Issue of layout: vertical vs horizontal
-How we could solve the current problem of too much information/content if we use the “all one page” vertical layout as recommended by research
	-P3 is most like our target user
	-P3; too much instruction for a simple task
	-P2 not representative of our target user
	-Frontloading action-based content, adding more info/examples after

Action Steps:
-We decided to create a mock-up of a new structure that could solve the above problem:
		Each page has three subpages
			Page 1.1 has a template and checklist (all you need to do the task)
			Page 1.2 has examples (more than two but not the big overwhelming chart)
			Page 1.3 has the “why”
		Key point: Only Page 1.1 is actually needed for the task ONE-STOP SHOP
		We think this will be most in line with how designers work in Figma
-We will present the mock-up at the next all-hands meeting
-Mock-up will be lo-fi

**Comment by allthatyazz** [comment]
# Since June 2022, we have implemented a team sandbox [(Whiteboard](https://www.figma.com/file/5NacfOm45QlrWgr6wWEg4k/Design-System-Template-for-HfLA?node-id=2%3A33)) and documented design decisions/ meeting highlights there.
