### ISSUE TITLE
Creating a Start Page for HfLA Design System Checklist

### ISSUE THREAD

**Issue by winoue90** [hackforla/design-systems#323]
```
### Overview
For the foundations of the project design system and to maintain consistent best practices, please follow the checklist below when creating a start page for your project’s design system

### Action Items
- [ ] Create an indication of where to start reading
- [ ] Type out an introduction to the project
- [ ] Include a link to the project wiki

### Resources/Instructions
[Creating a Start Page Figma Foundations Slide](https://www.figma.com/file/UvUJ0zT2EEIOoDQVdn6ApN/Design-Systems-Team-Figma?node-id=615%3A38841)

```
