### ISSUE TITLE
FF: Cover Page Overview

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/design-systems#392]
### Overview
REPLACE THIS TEXT -Text here that clearly states the purpose of this issue in 2 sentences or less.

### Action Items
- [ ] Add items to the list below as you work on a new section
- [ ] Create Issues for the following
  - [x] Tutorial & Template: Cover page #383 
  - [ ] Example Page: Cover page #384 
  - [x] Usability Test plan Cover Page #377  
 - [x] Design team informs the research team they are ready for the pilot to be conducted
 - [x] Design Team provides researchers feedback through a FigJam file (for example, if a designer has a specific question that hopes to find an answer through user's feedback.) 
 - [x] Research Team incorporates the designers' feedback into Test's script. 
 - [ ] Conduct the usability test

### Resources/Instructions

- [Figma Foundations]( https://www.figma.com/file/5NacfOm45QlrWgr6wWEg4k/Design-System-Template-for-HfLA?node-id=2%3A7) 
- [FigJam to exchange feedback between research and design](https://www.figma.com/file/mmvbxZ6lctjQneEeqTjC8O/UX%2FUI-Discovery-FigJam?node-id=0%3A1)
- [Google drive contains Usability Test plans](https://drive.google.com/drive/folders/1U7f9yH0VZgZPxtpAru5RL1LmIJo9ghfz?usp=sharing)
-
