### ISSUE TITLE
Analyze FF cover page usability test-Participant 2

### ISSUE THREAD

**Issue by hdchangie** [hackforla/design-systems#419]
# Introduction
The usability test with Participant B on the Figma Foundation cover page was conducted on April 28, 3 pm est/12pm pst via Zoom. The Zoom recording and audio can be found in Google Drive. Please watch the recording and generate your sticky notes in the Figjam. 

# Task

- [ ] Watch the usability test [here](https://drive.google.com/drive/folders/1Kih3WJvXYHTIw2RSnXCgzJDZnMonlS5T) and take notes during your viewing. 
- [ ] generate stickie notes in the [Figjam](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=0%3A1) for the analysis. 

# Files
[Google Drive Zoom recording ](https://drive.google.com/drive/folders/1Kih3WJvXYHTIw2RSnXCgzJDZnMonlS5T)
[Figjam](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=0%3A1)

**Comment by hdchangie** [comment]
# Analyzing session with participant 2
After completing these subtasks, scroll up to the top to check off the main task.
- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Watch the [recording in Drive](https://drive.google.com/drive/folders/1Kih3WJvXYHTIw2RSnXCgzJDZnMonlS5T) and observe participant behavior, and [take notes here](https://docs.google.com/spreadsheets/d/1kPUgCmxFp2X3cm33GvCbd41JzrfOYQye). Note-taking should take at least 1.5 times the length of the recording (i.e., a 30-min video will take at least 45 min to take notes on)
- [ ] Add [your insights in this Figma](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam)
- [ ] Below, summarize your recommendations for the design, future tests, the facilitating, etc.

**Comment by kelenelee** [comment]
# Analysis
After completing these subtasks, scroll up to the top to check off the main task.
- [ ] Read [article on analyzing usability tests](https://www.usability.gov/how-to-and-tools/methods/reporting-usability-test-results.html)
- [ ] Watch the [recording in Drive](https://drive.google.com/drive/folders/1Kih3WJvXYHTIw2RSnXCgzJDZnMonlS5T) and observe participant behavior, and [take notes here](https://docs.google.com/spreadsheets/d/1kPUgCmxFp2X3cm33GvCbd41JzrfOYQye). Ideally the notes should be detailed enough to take you at least 1.5 times the length of the recording (i.e., a 30-min video will take at least 45 min to take notes on)
- [ ] Add [your insights in this Figma](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam)
- [ ] Below, summarize your recommendations for the design, future tests, the facilitating, etc.
