### ISSUE TITLE
Milestones / Labels - cleanup & protocol recommendations

### ISSUE THREAD

**Issue by kelenelee** [hackforla/design-systems#425]
These tasks used to be part of #395. This is part of a greater effort to make the Github board less cluttered and less intimidating for newcomers

# Labels 
- [x] Add descriptions to labels so that people aren't left guessing what they are
- [x] Deleted duplicate or unused labels and milestones, and shortened label names to take up less space.
  - [x] replaced New Issue Approval and Questions/Review columns with label `?`
  - [x] shortened `priority: high` to `!`. Low and medium priority labels have been deleted, as they weren't used very much, and issues without a priority tend to default to being implicitly understood as low/medium priority.
- [x] Categorized groups of similar labels by emoji and color
  - [x] Colors contrast more to meet WCAG AAA standards. Light colors are light enough to not draw attention away from issue names. Dark label colors are used sparingly for high priority, new issue approval, questions/review. 
  - [x] Size point labels are gradients of yellow to communicate length of time. Emoji is hourglass and # of hours of work. Description changed to reflect HfLA schedule, i.e. 6 hours = 1 traditional work day = 1 HfLA week
  - [x] Roles now have the bust silhouette. For now, green is discipline and purple is management.

# Milestones 
- [x] Deleted milestone Velocity, because onboarding / meeting agendas never end and projects are supposed to progress toward an end goal. 
- [x] Reviewed documentation-related issues and created new milestones for them: Project revival for when the project was first being started, Transitioning... for when the team line up was changing a lot in late 2021, and New PM for when Hana left. 
- [x] Created a milestone for Figma Foundations usability tests and a milestone for design. As the project evolves, we'll revisit the issue structure and how it might combine with new labels.

**Comment by kelenelee** [comment]
The initial fixing of the milestones and labels is complete. Right now the original Figma Kit (Foundations) "epic" is still an issue, but it will be moved to the milestone description. 

### Reflections 
Milestones are as close to real epics as Github can get. The milestone page can populate a milestone description, the issues that fall under it, a due date, and a progress bar. The description can also contain links to issues with #`###`. 

At the start of this cleanup, milestones and labels were not used optimally. 

The milestones at the time were not projects with an end. The issues therein were better suited to being categorized by label or by project board. The milestones were also poorly described. The roadmap, which has now been marked as depreciated in our Drive, also did not clearly explain the purpose of the milestone.

The labels were poorly named, misunderstood, and not described. which lead to misuse and underuse, which then cluttered the dropdown menu. Names were not formatted consistently. There was no findable explanation for `feature` vs `p feature`. The lack of logic behind label colors led to visual distraction in the Kanban board.

At the beginning of this project. I assumed that this applied to feature labels, so I deleted them all. However, since the cleanup of the issues and the board has concluded, it may become clear that they can be added back and used properly across multiple milestones. While many of the labels were deleted, some users report having gotten used to and learned the basic labels of priority, approval/questions/review, and size points.

Our team (the end users of the Kanban board) were and are still intimidated and avoidant of Github. This is problematic because documentation is important for telling the story of the project history and understanding previous work. This also fails to prepare volunteers for their future career in the tech industry which frequently uses flavors of Scrum/Agile.
