### ISSUE TITLE
Iteration after P1 & P2

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#426]
## Overview
We need to make iterations to the design of Figma Foundations based on the insights from usability tests to meet user needs better before testing the design on more participants. 
 
## Background 
The first round of the usability test with 2 participants on the Figma Foundation cover page was concluded on April 28, 2022. During May 2 all-hands meeting, the team members (researchers and designers) generated sticky notes in Figjam for analysis together. The further discussion happened during the Design team meeting on Tuesday 5/4/2022. https://github.com/hackforla/design-systems/issues/264#issuecomment-1116889044

## Assignees 
- [x] @winoue90  
- [x] @tamalatrinh  
- [x] @JohnHaoHuang
- [x] @sandraberjan   

## Tasks 
 - Each Assignee makes a comment with the below template. Once you finish your design, come back to the checklist above and check off your name.

```
**Reiterate the design of different pages by [ your name]**
After completing these subtasks, scroll up to the top to check off your name in the main task.
- [ ] Review the report [Usability study analysis: Findings and recommendations](https://docs.google.com/document/d/1zJvP6aoOHSfICTW01w1o1JVcSxE7uJqC/edit?usp=sharing&ouid=105768861281432074552&rtpof=true&sd=true) by the research team
- [ ] Work on the design of the following pages in your Sandbox ( should be named after you) and as you work on a page/section please check the mark so we can track if there is a page that no one works on that. 
   - [ ] Start Here
   - [ ] Cover Page Instruction
   - [ ] Example page
   - [ ] Templates pages
- [ ] Below, add extra notes you may have regarding your process, challenges, recommendations for the design, future tests, the facilitating, etc. 
```
## Resources
[Figma Foundation](https://www.figma.com/file/5NacfOm45QlrWgr6wWEg4k/Design-System-Template-for-HfLA?node-id=2%3A22) 
[FigJam](https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=0%3A1)
[Usability Report](https://docs.google.com/document/d/1zJvP6aoOHSfICTW01w1o1JVcSxE7uJqC/edit?usp=sharing&ouid=105768861281432074552&rtpof=true&sd=true)

**Comment by winoue90** [comment]
**Reiterate the design of different pages by Wataru Inoue**
After completing these subtasks, scroll up to the top to check off your name in the main task.
- [ ] Review the report [Usability study analysis: Findings and recommendations](https://docs.google.com/document/d/1zJvP6aoOHSfICTW01w1o1JVcSxE7uJqC/edit?usp=sharing&ouid=105768861281432074552&rtpof=true&sd=true) by the research team
- [ ] Work on the design of the following pages in your Sandbox ( should be named after you) and as you work on a page/section please check the mark so we can track if there is a page that no one works on that. 
   - [ ] Start Here
   - [ ] Cover Page Instruction
   - [ ] Example page
   - [ ] Templates pages
- [ ] Below, add extra notes you may have regarding your process, challenges, recommendations for the design, future tests, the facilitating, etc.

**Comment by sandraberjan** [comment]
**Reiterate the design of different pages by Sandra**
After completing these subtasks, scroll up to the top to check off your name in the main task.
- [ ] Review the report [Usability study analysis: Findings and recommendations](https://docs.google.com/document/d/1zJvP6aoOHSfICTW01w1o1JVcSxE7uJqC/edit?usp=sharing&ouid=105768861281432074552&rtpof=true&sd=true) by the research team
- [ ] Work on the design of the following pages in your Sandbox ( should be named after you) and as you work on a page/section please check the mark so we can track if there is a page that no one works on that. 
   - [ ] Start Here
   - [ ] Cover Page Instruction
   - [ ] Example page
   - [ ] Templates pages
- [ ] Below, add extra notes you may have regarding your process, challenges, recommendations for the design, future tests, the facilitating, etc.

**Comment by JohnHaoHuang** [comment]
**Reiterate the design of different pages by [ your name]**
After completing these subtasks, scroll up to the top to check off your name in the main task.
- [ ] Review the report [Usability study analysis: Findings and recommendations](https://docs.google.com/document/d/1zJvP6aoOHSfICTW01w1o1JVcSxE7uJqC/edit?usp=sharing&ouid=105768861281432074552&rtpof=true&sd=true) by the research team
- [ ] Work on the design of the following pages in your Sandbox ( should be named after you) and as you work on a page/section please check the mark so we can track if there is a page that no one works on that. 
   - [ ] Start Here
   - [ ] Cover Page Instruction
   - [ ] Example page
   - [ ] Templates pages
- [ ] Below, add extra notes you may have regarding your process, challenges, recommendations for the design, future tests, the facilitating, etc. 
Resources

**Comment by sandraberjan** [comment]
05/10
I provided feedback on the designs for the Cover Page and Templates within Figma using comments
I created a copy structure and options for the landing page in Figma
I created two options for copy of the examples page with commentary in Figma

**Comment by tamalatrinh** [comment]
**Reiterate the design of different pages by [ your name]**
After completing these subtasks, scroll up to the top to check off your name in the main task.
- [ x] Review the report [Usability study analysis: Findings and recommendations](https://docs.google.com/document/d/1zJvP6aoOHSfICTW01w1o1JVcSxE7uJqC/edit?usp=sharing&ouid=105768861281432074552&rtpof=true&sd=true) by the research team
- [ x] Work on the design of the following pages in your Sandbox ( should be named after you) and as you work on a page/section please check the mark so we can track if there is a page that no one works on that. 
   - [x ] Start Here
   - [x ] Cover Page Instruction
   - [ x] Example page
   - [ ] Templates pages
- [ ] Below, add extra notes you may have regarding your process, challenges, recommendations for the design, future tests, the facilitating, etc.

**Comment by kelenelee** [comment]
After P1, P2, and P3 sessions, @sandraberjan @JohnHaoHuang @allthatyazz and I were discussing the following: 
- how much of the instructions can be baked into the template so that [users don't have to go back and forth between their file and ours?
- should text explanations be located in the kit, if PMs will be briefed by the stakeholder eventually?
- should we even consider Figma newbies as an end user?

Task analysis technique and examples here: https://www.figma.com/file/l911DJDfDo0Yr70lagjSmx/Usability-test-analysis-FigJam?node-id=247%3A956
