### ISSUE TITLE
Documenting Design Decisions: Create single source of truth 

### ISSUE THREAD

**Issue by sandraberjan** [hackforla/design-systems#432]
# BACKGROUND 

We need documentation of design decisions so that goals are clear, work is efficient, and we have better alignment across teams. 
Right now: The history of UX/UI is hard to understand. There are no GitHub issue templates specific to Design. Designers are not documenting in GitHub. 

### change log

# ACTION ITEMS

- [ ] Create an issue to point out the need for documentation
- [ ] Tag PM and leads to help with labeling of the issue
- [ ] Tag all designers and ask them to add their thoughts
- [ ] Share the slide deck Sandra made to summarise what she currently knows
- [ ] Ask others for input on slide deck

# SUBTASKS

**Comment by sandraberjan** [comment]
@allthatyazz @kelenelee @winoue90 Please help me edit and label this issue.

**Comment by sandraberjan** [comment]
Slide deck you can add to or comment on: https://docs.google.com/presentation/d/1vZtGb3oI6wdipXL-Gm8FVpi6l5AqmEW-TrZMJutIVPs/edit#slide=id.g13086665d6f_2_1

**Comment by sandraberjan** [comment]
@khanhcao17 @kangina-tech Would you say that you have a good system of communicating design decisions in place? If so, I want to close this issue. (I made this way before your time but I think the problems I raised then are all fixed now by your new organization efforts.)

**Comment by khanhcao17** [comment]
@sandraberjan Is this what you're talking about in terms of the communicating design decisions?

![image](https://user-images.githubusercontent.com/83927869/219484151-7c65f134-f655-49c4-bfdd-100ff812de02.png)

**Comment by sandraberjan** [comment]
@khanhcao17 Yes, that's exactly it.
