### ISSUE TITLE
Updating the repository Issue Templates for the Design Systems project 

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#450]
# Overview
We need to update the GitHub Issue Templates for the project so that the volunteers can have a consistent experience across different projects. 

# Background
As part of our GitHub clean-up effort in mid-2022, Kelene reformatted the Issue templates for the project. 

# ACTION ITEMS
- [ ] Include the relevant examples or guidance from different projects  
- [ ] Explore the blank issue that uses the Form feature ( [see the example from HfLA's Website](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-form-with-no-dependency.yml)) 
- [ ] Create/update the template 
- [ ] document the issue's background section with relevant info or screenshots

**Comment by allthatyazz** [comment]
# Internship project Sample instruction for Blank issues 

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by allthatyazz** [comment]
# FOLA Project: Sample Instruction for a Blank Issue

### Overview
REPLACE THIS TEXT -This should be in the form of a user story and why we are doing this. We need to do x for y reason.

### Action Items
REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by allthatyazz** [comment]
During the Product CoM meeting on Friday 1/6, we discussed the Form issues and as a result, I decided to overwrite the previous template created by Kelene. Just the be on the safer side, I duplicated the raw content from Kelene's template below.

 ---
name: 📝 Standard template
about: Tips for writing a good issue are included inside. --------
title: ''
labels: '?,'
assignees: ''

---
# BACKGROUND 




### change log


# ACTION ITEMS

- [ ] As you complete the tasks, make comments adding your thought process, i.e., "Teammate x and I collaborated on this task in this Figma file: http... We decided that the most important takeaways from the participant 1 session was y. Based on y, we recommend design changes a, b, and c, because... Update, we discussed a, b, and c in the all-hands meeting last week and our recommendations are set to be completed next month, and is being documented in issue #..."

# SUBTASKS


```
- [ ] Repeated subtask
- [ ] Repeated subtask
```
