### ISSUE TITLE
Design Systems: All Team- 2023 Agneda

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#478]
### Overview

This issue tracks the agenda for the design systems all-team meetings. This will help us stay focused on the goal and move on the research plan in a timely manner. Weekly meetings for the Research team occur on Mondays at 5:30 pm PST. 

#### Template
```
# Month Day, Start time - End time
Attendees @ @ @ @ @
- [Relevant issues assigned to the research team](https://github.com/hackforla/design-systems/labels/%F0%9F%91%A4%20Research) 
- Links
- Topics discussed
- Decisions made
### MOVING FORWARD 
- Tasks for next week 
```

### Resources/Instructions

- Previous Agenda #26

**Comment by allthatyazz** [comment]
# 1/9
Attendees : Yas, Wataru, Sandra, Rachel, Khanh, Faezeh, Eva + New Joiners
- This was the first meeting of 2023. The team received a lot of interest from the new volunteers to join the team.
-  Team members and new joiners introduced themselves.
- We talked about the Figma Kit and the roadmap for 2023. 

### MOVING FORWARD 
- Team Leads to meet regularly to make sure the pods are in sync. 
- New joiners to follow up with their team leads and start the onboarding

**Comment by allthatyazz** [comment]
# 1/23
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees @ @ @ @ @

**RECURRING ITEMS**
- [ ] Updates from each lead regarding the tasks that have been done in the last week
- [ ] Review project board and assignments 
# Agenda 
**FYI** : This is a workshop session for UXRs and UXDs to collaborate on the research design for the upcoming user testings. 
- [ ] A quick demo of Figma Kit as the end users would experience it (10 mins)
- [ ] Researchers present their work (20 mins)
- [ ] Open mic for questions and thoughts (20 mins)
# Meeting Notes and Highlights
- Decisions made
### MOVING FORWARD 
- [ ]Tasks for the week

**Comment by allthatyazz** [comment]
# 1/30
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees @ @ @ @ @

**RECURRING ITEMS**
- [ ] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
- [ ] Review project board, assignments, or blockers if any
# Agenda 
**FYI**: After an initial 10-15 min team standup, there would be an active work session for each pod to work/design with their teammates.  
- [ ] Short announcement: Plan for mock user tests with Asad, Michael, or Liz in the week of  2/6-2/10. 
- [ ] Create breakout rooms for DESIGN+CONTENT and RESEARCH. 
- [ ] RESEARCH breakout room:
  - [ ] Pick up work from the last research meeting: work on the rest of the questions/parts that the team did not have time to get to.
  - [ ] Focus on the parts that are currently missing in the research plan.
 - [ ] DESIGN breakout room: 
   - [ ] Collaborate on wireframes or mockups with your teammates based on action items from https://github.com/hackforla/design-systems/issues/464#issuecomment-1397787735
# Meeting Notes and Highlights
- Decisions made
### MOVING FORWARD 
- [ ] Tasks for next week

**Comment by allthatyazz** [comment]
# 2/6
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees @ @ @ @ @

**RECURRING ITEMS**
- [ ]Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
- [ ] Review project board, assignments, or blockers if any
# Agenda 
**FYI** <The research team is done with their questions. We would conduct a mock user test with Asad to test the research plan before conducting the actual interviews>
- [ ] PM Updates the team after the stakeholder meeting
- [ ] Mock Interview
# Meeting Notes and Highlights
- Decisions made
### MOVING FORWARD 
- [ ] Tasks for next week

**Comment by allthatyazz** [comment]
# 2/13
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees @ @ @ @ @

**RECURRING ITEMS**
- [ ] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
- [ ] Review project board, assignments, or blockers if any
# Agenda 
**FYI**  At tonight's meeting, we will have our very first "dogfooding".  Our dogfooding experience might be a little different than conventional UX dogfooding where product or dev teams test a product or feature internally. Asad will help researchers in a role-playing exercise to evaluate their research plan and script. So the goal is not really to test the usability of our product, the Figma Kit,  but the usability of the research plan.

- [ ] Introduction: Welcome Josh to the team
- [ ] The project roadmap and the workflow for the team  
- [ ] Mock User testing (30-40 mins)

# Meeting Notes and Highlights
- Decisions made
### MOVING FORWARD 
- [ ] Tasks for next week

**Comment by allthatyazz** [comment]
# 2/27
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees @ @ @ @ @

**RECURRING ITEMS**
- [ ] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
- [ ] Review project board, assignments, or blockers if any
# Agenda 
**FYI** In this session, the Research team shares the preliminary findings and interesting observations from the first 4 user tests with the rest of the team.
- [ ] Greetings and Standup (10 mins)
  - [ ] PM
  - [ ] Content Lead
  - [ ] Design Leads
  - [ ] Research Leads
- [ ] Research shares insights (20-35 mins)
- [ ] Q/A and Open discussion (15-20 mins)
- [ ] Wrap (5 mins)
# Meeting Notes and Highlights
- Decisions made
### MOVING FORWARD 
- [ ] Tasks for next week

**Comment by allthatyazz** [comment]
# 3/6
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees @ @ @ @ @

**RECURRING ITEMS**
- [ ] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
    - [ ] PM
    - [ ] Design
    - [ ] Reseacrh
    - [ ] Content
- [ ] Review project board, assignments, or blockers if any
# Agenda 
**FYI** 
- [ ] Q from Eli = Affinity Mapping?
- [ ] Timeline for assignments
# Meeting Notes and Highlights
- Decisions made
### MOVING FORWARD 
- [ ] Tasks for next week

**Comment by allthatyazz** [comment]
# 3/13
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees @ @ @ @ @

**Pre Work**
- [ ] Read the previous meeting notes

**RECURRING ITEMS**
- [ ] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
  - [ ] Design Lead
  - [ ] Content Lead
  - [ ] Research Leads
  - [ ] PMs
- [ ] Review project board, assignments, or blockers if any
# Agenda 
- [ ] Standup (20-30 mins)
- [ ] Q/A (10 mins)
# Meeting Notes and Highlights
- Decisions made
### MOVING FORWARD 
- [ ] Tasks for next week

**Comment by allthatyazz** [comment]
# 3/27
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees @ @ @ @ @

**RECURRING ITEMS**
- [ ] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
- [ ] Review project board, assignments, or blockers if any
# Agenda 
**FYI** The research team presents the final insights report.
- [ ] Research Presentation (25 min) 
- [ ] Q and A (10 min)
- [ ]  Standup (15 min) 
# Meeting Notes and Highlights
- Decisions made
### MOVING FORWARD 
- [ ] Tasks for next week

**Comment by allthatyazz** [comment]
# 4/3
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees 

**RECURRING ITEMS**
- [ ] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
- [ ] Review project board, assignments, or blockers if any
# Agenda 
- [ ] Standup (20-30 min, each team ~ 10 min)
  - [ ] Design 
    - [ ] Review the progress for #507 
  - [ ] Content
  - [ ] Research
- [ ] Plan for stakeholder meeting on 4/17
- [ ] Review the Kanban Project Board
  - [ ] Brief explanation of the board for none present people
  - [ ] Demo ways to insure the documentation is complete before closing an issue. 
  


# Meeting Notes and Highlights
- Decisions made
### MOVING FORWARD 
- [ ] Tasks for next week

**Comment by allthatyazz** [comment]
# 4/10
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees Eli, Zeynep, Khanh, Asad, Michael, Michelle, Sandra, Jiyon, Josh, and Yas

**RECURRING ITEMS**
- [ ] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
- [ ] Review project board, assignments, or blockers if any
# Agenda 
**FYI** This is going to be a namestorming session to choose consistent naming for our products.
- [ ] Standup (15 mins)
  - [ ] Design
  - [x] Content
  - [x] Research
- [ ] Namestorming session (30 mins)
  - [ ] #509 
  - [ ] #510
- [x] Q/A and Warp ups 
# Meeting Notes and Highlights
- Sandra (the content lead) made a presentation on best practices for naming products. 
  - Good product names start with understanding the user's mental models.
  - Before the naming exercise, we have to set some principles for the naming and create criteria.
 - After Sandra's presentation, the team agreed on postponing the namestorming to follow the right standards suggested by Sandra. 
 - Sandra will take a lead on setting a timeline for our naming initiatives. Some of the tasks can be done async. 
 - The latest working titles suggested by the content team for our internal use are Figma Guide and Design Systems Starter Kit. 
### MOVING FORWARD 
- [ ] Yas is making an issue for bug and other quick fixes in v1.0 of the Figma Kit/Guide and making the Kit ready for v1.1
- [ ] Khanh and Sandra will help with v1.1 .

**Comment by allthatyazz** [comment]
# 4/17
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees Khanh, Asad, Liz, Gala, Zeynep, Eli, Faezeh

**RECURRING ITEMS**
- [x] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
- [x] Review project board, assignments, or blockers if any
# Agenda 
**FYI**  Content team will lead a name-storming on 4/24! 
- [ ] Content Updates
   - [ ] Sandra talks about some of the desk research that needs to be done.
   - [ ]  Discuss if anyone on the research team is interested in being involved
- [x] Research Updates
   - [x]  Research asks the Design team to familiarize them with the DS Starter.
- [x]  Design Updates
   - [x] The roadmap for components #507
   - [x] Liz' update on Menu component
# Meeting Notes and Highlights
- Research- The research team is waiting for a demo of components the design team is working on. Once the demo is available, the research team will better understand what direction they need to go in for questions that need to be asked. 
- Design- The design team is working on solidifying the components demo for the research team. Presently, color has been completed, they are working on typography and finishing the buttons. Asad and Natalie also working on individual components. Liz presented her menu components as well as the research she conducted. The design team is hoping to have at least 5 components in a couple of weeks for the demo. 
- Content- Sandra was unable to attend the meeting.
### MOVING FORWARD 
- [ ] Tasks for next week

**Comment by allthatyazz** [comment]
# 4/24
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees Yas, Sandra, Michelle, Zeynep, Eli, Faezeh, Asad, Khanh, Michael, Jiyon

**RECURRING ITEMS**
- [ ] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
- [ ] Review project board, assignments, or blockers if any
# Agenda 
**FYI : This is a Namestorming session led by the content team**. 

# Meeting Notes and Highlights
- The team collaborated on a FigJam for naming of the two products #509 and #510. 
### MOVING FORWARD 
- [ ] Content team to assess the stickies generated through this session and share their expert opinion with the team

**Comment by allthatyazz** [comment]
# 5/8
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees Zeynep, Eli, Khanh, Michelle, Asad, Sandra

**RECURRING ITEMS**
- [ ] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
- [ ] Review project board, assignments, or blockers if any
# Agenda 
**FYI** The theme would be planning and roadmap for the rest of 2023. The meeting will be divided into sections; the first half: the current stage and 2nd half: the future tasks. We may cut sharp right in the middle to make sure we have time to discuss all the agenda items. 
- [ ] Greetings and celebrating team members' recent accomplishments ( ~0-5 mins)
  - [x] Sandra's graduation from the team and Michelle's promotion to the lead role
  - [x] Khanh's new position and competition
  - [x]  Yas to share a few tips about effective use of GitHub issues ( ~ 3- 5 mins)
 - [x]  Standup ( ~15 -20 mins): we will do standup in a new format. As a team, we will go through the project board together and look at each pod's issues and address the questions. 
   - [x] Research 
   - [x] Content
   - [x] Design
  - [ ] Roadmap planning discussion ( 30 mins) 
  
# Meeting Notes and Highlights
- Few tips regarding the use of GitHub have been shared (e.g how to filter based on milestones/labels, work on existing issues, vs creating new ones and avoid creating too many similar issues). PM encouraged everyone to explore GitHub.   
- The project board has been reviewed in the traditional HfLA way ( We discussed issues by filtering based on each team's labels.)
 - The planning [FigJam](https://www.figma.com/file/Yv8hGuiraQVgrlNz1BF0gN/Product-Roadmap%2C-DS-labels%2C-milestones%2C-project-board-organization?type=whiteboard&node-id=0%3A1&t=4yCQQka00rm7WHPQ-1) was shared with the team. The idea was for the team member to collaborate. Team members shared concerns and tried to find common ground. 
 - PM has confirmed that she is not a project manager and does not focus on project management but more on product strategy and ensuring all the roles within the team are working towards the shared vision and helping the product and organization. 
 
### MOVING FORWARD 
- [ ] Tasks for next week

**Comment by allthatyazz** [comment]
# 5/15
**[ROLL CALL](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=1199107562)**
Attendees @ @ @ @ @

**RECURRING ITEMS**
- [ ] Standup:  Updates from each lead/ or team member regarding the tasks that have been done in the last week
- [ ] Review project board, assignments, or blockers if any
# Agenda 
- [ ] PM Talks about HfLA's code of conduct (5 mins)
- [ ] PMs show the new GitHub milestones (10 mins)
- [ ] Standup 
  - [ ] Content: Ask the content team to share their process on the naming activity 
    - [ ] Q/A to address the researcher's questions
# Meeting Notes and Highlights
- Decisions made
### MOVING FORWARD 
- [ ] Tasks for next week
