### ISSUE TITLE
Create open role for Content Designer

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/design-systems#483]
### Overview

With an influx of new joiners for HfLA in January 2023, we need to create a open role ticket for more UX writers/ Content Designers so there would be a balance between the number of UX designers and the content designers.

### Background

The next HfLA's onboarding happens on 1/31. We ideally need to post the role before the general onboarding.

### Tasks for Content Lead
- [x] Review the following resources below
- [ ] Write an open role for content designers
- [ ]  Add copy to this Issue
- [ ] Inform PM and ask for feedback

### Tasks for PM
- [x] Post on UX-UI community of practice 
  - [x] [GitHub](https://github.com/hackforla/UI-UX/projects/3)
  - [ ] Slack 
     - [ ] # UX-UI
     - [ ] # General
     - [ ] #new-joiner-orientation

 

### Resources/Instructions

[Example 1:  our job posting for UX Research role](https://github.com/hackforla/UI-UX/projects/2#card-86765658)
[Example 2: Expunge Assist's posting for UX Writers ](https://github.com/hackforla/UI-UX/projects/3)

**Comment by allthatyazz** [comment]
This is a temporary text that I put together before the content lead (Sandra) comes up with her own or edits the existing one. 

<img width="988" alt="" src="https://user-images.githubusercontent.com/6236085/149429778-04836ba9-0ff4-4ff8-88b4-9ff9f2d5cea0.png">

 **Project Name**: Design Systems Team

**Volunteer Opportunity**: The DS team is seeking a couple of Content Designers/UX writers. In the past, our project helped many volunteers including transitioning academics land new roles in the industry. 

We are looking to hire 2 highly-motivated content designers. We have recently launched our [MVP](https://github.com/hackforla/design-systems/releases/tag/v1.0) and our 2023 Q1-Q2 roadmap will be conducting user testing on the product and creating new content for the upcoming releases. 
[Read more about the project](https://github.com/hackforla/design-systems)

**Duration**: Open Ended (ideally those who could stay till June 23 )

**Who to communicate your interest to**
This project is on the Hack for LA Slack workspace ([get an invite here](https://hackforla-slack.herokuapp.com/))  
- Slack channel link: #[design-systems]

- Slack name of the persons to contact in the channel : @Yas Roostaeian, PM and @Sandra Berjan, Content Lead

**Comment by sandraberjan** [comment]
@allthatyazz  When is the next onboarding?

**Comment by allthatyazz** [comment]
@sandraberjan The next onboarding is today (2/13/2022)!  The onboarding dates can be found [here](https://www.meetup.com/hackforla/events). 

No worries if you can not update the message. I think what we have posted so the job board is good for NOW. 

- IMO it would be better to first establish a clear roadmap for the content team. Then we decide how many content designers we need to onboard. 
- My original idea was to have at least 3 people on the content team so we can partner each with a designer so we will have pairs of UX +Content buddies. But, based on the roadmap, maybe we can onboard even more.  For example, if we add the Wiki rewrite to the content team roadmap we can bring on a new person who would only work on that...  The challenge is the bigger the team become, the harder the people + task management will be.

**Comment by sandraberjan** [comment]
@allthatyazz Got it! Let's talk more this evening about the roadmap.

**Comment by allthatyazz** [comment]
The current job posting has been working well and we got two new content designers as a result.
