### ISSUE TITLE
Prep project boards for Migration

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/design-systems#528]
### Overview
We need to prepare the Project Boards for the forced migration that GitHub is doing in August, so that it is already working well for the team by then.

### Action Items
Repeat first 3 steps for each card
- [x]  copy this template to a comment below
   ````
   ### Text from project board card, [Add name of board here], [Add name of column here]
   ```
   [PASTE CARD CONTENT HERE]
   ```
   - [ ] Determine where this item goes on the wiki (page and section)
   - [ ] copy item to wiki
   - [ ] hide this comment when completed.
   ````
- [x] copy the content of the card (by clicking the 3 dots and selecting Edit Note, and then CRTL+C) and paste it into your new comment where it says `[PASTE CARD CONTENT HERE]
- [x] delete card from project board
- [x] add project board URL(s) in resources below
- [x] add the `project board migration` label to this issue
- [ ] add issue to project board
- [ ] move issue to Prioritized Backlog

### Resources/Instructions
Classic Project board URL(s):
- Open:
  - [Documentation](https://github.com/hackforla/design-systems/projects/7)
  - [Learning about design systems](https://github.com/hackforla/design-systems/projects/4)
  - [DS Team Initiatives](https://github.com/hackforla/design-systems/projects/1)
- Closed:
  - [Interview study](https://github.com/hackforla/design-systems/projects/6)
  - [Surveying the onboarding experience](https://github.com/hackforla/design-systems/projects/5)
  - [Guides and Templates for Design System](https://github.com/hackforla/design-systems/projects/3)
  - [Design System Template](https://github.com/hackforla/design-systems/projects/2)

New Project board URL(s): None

**Comment by Rabia2219** [comment]
### Text from project board card, Documentation, ABOUT
```
###### [🔙 to other boards](https://github.com/hackforla/design-systems/projects)
___
###### [Why was this board created?](https://github.com/hackforla/design-systems/milestone/23)
___
### Milestone filters
[🚩 Project revival](?card_filter_query=milestone%3A%22project+revival%22#card-81016320)
[🚩 Transitioning to new team lineup](?card_filter_query=milestone%3A%22transitioning+to+new+team+lineup%22#card-81016320)
[🚩 User needs interviews](?card_filter_query=milestone%3A%22user+needs+interviews%22#card-81016320)
[🚩 Github heuristic evaluation](?card_filter_query=milestone%3A%22github+heuristic+evaluation%22#card-81016320)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, DS Team Initiatives, START HERE
```
[Project one sheet (Six-month Roadmap)](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Design-Systems-One-Sheet.pdf)

### Links

- Make a [new issue](https://github.com/hackforla/design-systems/issues/new/choose)
- See [Google Drive](https://drive.google.com/drive/folders/1BE2bwPuBxKWtQPGw-Mn1pEvDGivawaRp?usp=share_link) (for DS members only)
- See [Figma Project](https://www.figma.com/files/project/39879901/Design-Systems-Team-Folder?fuid=874819519832324563) (for DS members only)
___
### Meetings
###### (Pacific time)
- Team: Mon 5:30pm, [Zoom](https://us02web.zoom.us/j/84568818415?pwd=WkNzWUtTa01Td3d3NWlLQTk2VDlkdz09)
- UX/UI: Thurs 10:30am, [Zoom](https://us02web.zoom.us/j/82859066994?pwd=YUlqajlGM3BKeU5qbUU1Uk9ndVIzZz09)
- Research: Wed 1:30pm, [Zoom](https://us06web.zoom.us/j/89508717591?pwd=M2JiSVUwdjRTSjV3WUdTdUFaT1ltUT09)
- Content: Wed 3pm, [Zoom](https://us02web.zoom.us/j/85049697330?pwd=N3lyQy9CMmpjM)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, DS Team Initiatives, ICE BOX 
```
Team "inventory" https://github.com/hackforla/product-management/issues/270
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, DS Team Initiatives, ICE BOX 
```
[PASTE CARD CONTENT HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.
