### ISSUE TITLE
Create Roadmap

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#64]
### Overview
As a product manager, I need to create a roadmap each 6 months so that the website team work more efficiently.

### Action Items

- [x]  Create milestones from prioritization framework
- [x]  Check milestones with Bonnie
- [x]  Create milestones filters
- [x]  Prioritize the prioritized backlog
- [x]  Check filters and milestones with Bonnie
- [x]  Prioritize all the issues in the Prioritized Backlog by Milestone
- [x]  Review all the Milestones to make sure that all the issues necessary to complete the milestone are included.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by Hanastevenson** [comment]
To be reviewed #117
