### ISSUE TITLE
Create the Research Roadmap 

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#74]
### Overview
Create a research roadmap that states the research objectives, assumptions, research methods and proposed timeline. 

### Action Items

- [ ] From the Assumptions document #52 
- [ ] Review the the documents below
- [ ] Create the roadmap
- [ ] Send to Mina to review
- [ ] Once approved send to PM
- [ ] Share in a team weekly meeting

### Resources/Instructions
[Guide: How to make a Research plan -draft](https://docs.google.com/document/d/1lTmjiAzSwiUOFD4f4eGs0WGktaqZ6ogx_fiXhP7oR9U/edit)
