### ISSUE TITLE
Weekly Agenda PM and Stakeholder

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#89]
### Overview
This issue tracks the agenda for the stakeholder and PM of design systems meetings.

### Weekly Agenda
[Week 2021/08/30](https://github.com/hackforla/design-systems/issues/72)

### Resources/Instructions
[Zoom meeting](https://us02web.zoom.us/j/4451450308?pwd=U0JobzZqN0xGSXBUUkRsNlB5YzJiQT09)

**Comment by Hanastevenson** [comment]
24th January Agenda and Notes

### Pre work
- [ ] Create new links for new meetings #282 

#### Recurring items: Happens on the PM Monday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/internship/projects/1#column-15516595)
 - [ ] Who and where do I need to post new meeting times
- [ ] Access to the one password
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/design-systems/issues/assigned/ExperimentsInHonesty)
       - [ ] [Hana](https://github.com/hackforla/design-systems/issues/assigned/Hanastevenson)


#### New Items
#### Task items from Team meeting to review
- [ ] 

- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by Hanastevenson** [comment]
31st March Agenda and Notes

### Prework


### Roll Call

#### Recurring items: Happens on the PM Monday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/internship/projects/1#column-15516595)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/design-systems/issues/assigned/ExperimentsInHonesty)
       - [ ] [Hana](https://github.com/hackforla/design-systems/issues/assigned/Hanastevenson)

#### New Items

- [ ] Run through of project


#### Task items from Team meeting to review
- [ ] New joiners and leavers for the project page on HfLA . https://github.com/hackforla/design-systems/issues/302

- [ ] 
  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by allthatyazz** [comment]
3/2/2/22 Agenda and Notes

### Prework
- [ ] Attend DS weekly meetings

### Roll Call

#### Recurring items: Happens on the PM Monday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/internship/projects/1#column-15516595)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/design-systems/issues/assigned/ExperimentsInHonesty)
       - [ ] PM


#### New Items
       - [ ] Ask for Bonnie's help with setting up the zoom account
       - [ ] Discuss new members (Cherilyn and Tammy)
       - [ ] Discuss the usability testing 
#### Task items from Team meeting to review

  - [ ] Carry forward the "New Items" that we did not get to look at today

### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by allthatyazz** [comment]
3/2/2/22 Agenda and Notes

### Prework
- [x] Get initial feedback from the team about usability study 
 
### Roll Call

#### Recurring items: Happens on the PM Monday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/internship/projects/1#column-15516595)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/design-systems/issues/assigned/ExperimentsInHonesty)
       - [ ] PM


#### New Items
  - [ ] Jeanette talks about the Survey Plus service
  - [ ] Discuss the new product roadmap for release of MVP (DS template and totorial)
  - [ ] Discuss the usability testing 
#### Task items from Team meeting to review


### FYI

### Notes from meeting
- 

### New Task Items

#### Items for next week's agenda

**Comment by allthatyazz** [comment]
3/14/22 Agenda and Notes

### Prework
 
### Roll Call

#### Recurring items: Happens on the PM Monday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/internship/projects/1#column-15516595)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/design-systems/issues/assigned/ExperimentsInHonesty)
       - [ ] PM


#### New Items
  - [ ] Discuss the PRD document Yas prepared for the team. 
 
#### Task items from Team meeting to review


### FYI



### Notes from meeting


### New Task Items

#### Items for next week's agenda

**Comment by allthatyazz** [comment]
3/21/22 Agenda and Notes

### Prework
 -[ ] Confirm with Bonnie if she can attend the team meeting or not. If Bonnie can attend the team meeting on Monday night, Yas does not need to present the work to Bonnie, and research team members can ask her their questions directly. 

### Roll Call

#### Recurring items: Happens on the PM Monday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/internship/projects/1#column-15516595)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/design-systems/issues/assigned/ExperimentsInHonesty)
       - [ ] PM


#### New Items
  - [ ] Continue the Figma Audit work and check the relevancy of the newly added columns to the audit. 
  - [ ]  GitHub Board management.
  
 
#### Task items from Team meeting to review


### FYI



### Notes from meeting
 - 

### New Task Items

#### Items for next week's agenda

**Comment by Providence-o** [comment]
Please add to your next agenda

- Discuss with Bonnie you adding this [CTA](https://docs.google.com/presentation/d/1UDHwTQ1C3y01CiNS0mvPjNBHJFlm2Txs/preview) to your team agenda

**Comment by ExperimentsInHonesty** [comment]
@allthatyazz We are trying to secure some social media accounts for your team.  It seems like your team has already setup an Instagram account using the email address designsystems@hackforla.org, but we don't know what it's username is?  I don't see any issues with the word Instagram in it. Please reach out to Hana to find out if she knows anything about it.

**Comment by allthatyazz** [comment]
> @allthatyazz We are trying to secure some social media accounts for your team. It seems like your team has already setup an Instagram account using the email address [designsystems@hackforla.org](mailto:designsystems@hackforla.org), but we don't know what it's username is? I don't see any issues with the word Instagram in it. Please reach out to Hana to find out if she knows anything about it.
 
@ExperimentsInHonesty Thank you for bringing this to my attention. There is also no email in our inbox indicating that we previously had set up an IG account, however, there is a verification code sent by Instagram on March 22. I will reach out to the previous PM to get more detail.

**Comment by allthatyazz** [comment]
### Notes from meeting on 4/4/2022
 - PM asked for Stakeholder's help to complete the new Figma Audit for HfLA's teams. There were some teams with missing Figma links. The DS team has now access to the main Figma files of the projects who work with Figma. 
 -  We went through the latest team's progress on Figma Foundations and Stakeholder gave feedback on the following items: 
    - A better design for the Cover page is requested by Stakeholder that would match the Design Systems team's color palette and branding.
    - The introduction page name was changed to _Start Here_.
    - Information Architecture of into section has been modified and subpages are all merged into a single Page. 
    - Stakeholder expressed satisfaction with the new grading system that rates the examples from different Hack for LA projects.

**Comment by allthatyazz** [comment]
**4/11/22 Agenda and Notes**

### Prework
 - [ ] Prepare a list of potential participants for Usability Study. 

### Roll Call

#### Recurring items: Happens on the PM Monday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/internship/projects/1#column-15516595)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/design-systems/issues/assigned/ExperimentsInHonesty)
       - [ ] PM


#### New Items
   - Quick checks
   - [ ] Discuss with Bonnie you adding this [CTA](https://docs.google.com/presentation/d/1UDHwTQ1C3y01CiNS0mvPjNBHJFlm2Txs/preview) to your team agenda
   - [ ] Instagram Follow-up
   - Discuss in detail
  - [ ] Discuss the team's progress. 
   - [ ] New Epic issues: What is the best way to handle Epic? Can we always keep the epics open in a certain column so that when we work on task/bug issues tasks are associated with the Epics, we could effectively reference the child tasks to active Epics?  
  
 
#### Task items from Team meeting to review


### FYI



### Notes from meeting


### New Task Items

#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**4/20/22 Agenda and Notes**

### Prework


### Roll Call

#### Recurring items: Happens on the PM Monday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/internship/projects/1#column-15516595)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/design-systems/issues/assigned/ExperimentsInHonesty)
       - [ ] PM


#### New Items
   - Quick checks
   - [ ] Drive Privacy

   - Discuss in detail
    - [ ] Discuss the team's progress. 
     - [ ] Discuss the recent reorganization of GitHub board 
  
 
#### Task items from Team meeting to review


### FYI



### Notes from meeting
 - We went through the recent developments with Figma Foundations, and Bonnie gave quick feedback.  
 - Bonnie helped a lot to re-structure the Epic for Figma Foundations (FF) #376  . 
 - As a result we now have a template that can be reused for research and design leads for other FF sections. #392 
 

### New Task Items

#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**4/20/22 Agenda and Notes**

### Prework


### Roll Call

#### Recurring items: Happens on the PM Monday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/internship/projects/1#column-15516595)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/design-systems/issues/assigned/ExperimentsInHonesty)
       - [ ] PM


#### New Items
     - [ ] Discuss the team's progress in regards to the usability tests. 
     - [ ] Ask about the Planning Week?
  
 
#### Task items from Team meeting to review


### FYI



### Notes from meeting



### New Task Items

#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**5/9/22 Agenda and Notes**

### Roll Call

#### Recurring items: Happens on the PM Monday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/internship/projects/1#column-15516595)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/design-systems/issues/assigned/ExperimentsInHonesty)
       - [ ] PM


### New Items
 -  [ ] Ask about new volunteers recruitment, where to post (is it OK to use personal LinkedIn to promote the open roles ... )
 - Follow up on the Website team Start Here page. 
 - [ ] Discuss the team's progress in regards to the usability study
  

  
 
### Task items from Team meeting to review


### FYI



### Notes from meeting
- We discussed the items that should be included on the Start here page. We reviewed HUU and the Website team's Figmas to assess the relevance of the content on their Start Page. 
- Bonnie will follow up with the website team to update their developer's start here content on their Figma File.


### New Task Items

#### Items for next week's agenda

**Comment by ExperimentsInHonesty** [comment]
You never signed off on this https://github.com/hackforla/website/issues/2745.  Can I confirm that it was completed (by leaving a LGTM comment)?  If you have new people to add or remove, [please open a new issue for changes](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)

**Comment by allthatyazz** [comment]
**6/6/22 Agenda and Notes*



### New Items
 - [ ]Update Bonnie about the team's progress
 - [ ] Discuss the latest changes on HfLA's Figma Kit
 - [ ] Ask Bonnie to help update the Project Description
 
  

  
 
### Task items from Team meeting to review


### FYI


### Notes from meeting



   
    
#### Items for next week's agenda

**Comment by allthatyazz** [comment]
**6/20/22 Agenda and Notes**



### New Items
 - [ ] Update Bonnie about the team's progress
 - [ ] Discuss the latest changes on HfLA's Figma Kit
    - [ ] Discuss the requirements for new sections
 - [ ] Ask Bonnie to help update the Project Description https://github.com/hackforla/design-systems/issues/422#issuecomment-1144214719
 
  

  
 
### Task items from Team meeting to review


### FYI


### Notes from meeting



   
    
#### Items for next week's agenda

**Comment by allthatyazz** [comment]
# 10/17 
We discussed the necessity to push the product out of the door before the end of the year. As a result of this meeting, PM took the following actions. 
- Updated the team and required the team to wrap up V1 in 2 weeks. 
- Clarified the deadlines for the team. https://github.com/hackforla/design-systems/issues/263#issuecomment-1293761975

**Comment by allthatyazz** [comment]
# 11/7
The stakeholder approved the plan for release to UX-UI CoP. We walked through the final touch-ups required for the v1.0 release. We also discussed the logistics of the release. After this meeting, PM took the following actions. 
- [ ] creating a checklist of tasks based on the talk with the Stakeholder. https://github.com/hackforla/design-systems/issues/445
- [ ] Contacting the CoP leads (Sara Brady and )  and asking for a 10-min presentation time.

**Comment by ExperimentsInHonesty** [comment]
We will be reviewing the design-systems@hackforla.org email box to see if you can unsubscribe or at least tune the notifications from
sogolytics.com
getenjoyhq.com

**Comment by allthatyazz** [comment]
# 2/6 Agenda
Yas's Items
- [ ] Project one sheet update
- [ ] Team latest work

Bonnie's Items
- [ ] We will be reviewing the design-systems@hackforla.org email box to see if you can unsubscribe or at least tune the notifications from
   - [ ] sogolytics.com
   - [ ] getenjoyhq.com
   - [ ] calendly
- [ ] Please explain how you are using live notes on your team.  If its helpful we might roll it out to all teams.  Also want to hear how we using it and if its GDPR compliant ([my link](https://mail.google.com/mail/u/0/?tab=rm&ogbl#label/To+Do%2FIn+Progress/FMfcgzGpHHLLQWkVLHPMDvrXHbVvrmJL))
- [ ] All the projects need to have the label `feature: agenda`.  I have revised your label `agenda` to reflect this requirement.  I am happy to explain how the guides team will be using this label to help people find the agendas of all projects.
  - [ ] let's also discuss the emojis that you are using on the labels (very innovative)

**Comment by allthatyazz** [comment]
# 2/20 
- [ ] Updates from the team 
   - [ ] HfLA Design Systems Template
   - Josh has met with Design Leads (Debbie and Khanh).
     - We dug into the history of the project. 
     -  Design Leads believe adding code and specs to Figma reduces the usability for designers. 
   - Josh and Yas discussed some initial plans for phases.
      - Phase 1 the sticker sheet: polishing the existing components and making some essential components that are currently missing, Phase 2 specs: Adding specs such as visual indicators and annotation for developers in Figma, Phase 3 tokens or code snippets: Creating a code documentation library with Storybook or a similar tool. 
   - Ava Li from Civic tech jobs is interested to join us to help develop the DS.  After Eva reached out, I am thinking that Phase 1 and Phase 3 can be done in tandem. I really love to advocate for HfLA to use design tokens (I really like [this example from Amazon’s Style Dictionary](https://amzn.github.io/style-dictionary/#/tokens?id=design-token-structure)) . So maybe while Khanh and Debbie working on the sticker sheet, Eva can do research on how we can have a fully tokenized DS.  If we end up using a documentation tool like Storybook, I do not think we ever need Phase 2!
   - [ ] HfLA Figma Kit 
     - [ ] Design team is working on adding content for "Housekeeping rules."
     - [ ] Researchers started recruiting participants to test v1.0.  The first interview was conducted last week.

**Comment by sandraberjan** [comment]
"DANIELLE NEDIVI's [case study](https://www.daniellenedivi.com/hack-for-la-case-study) is actually the history of building the website team DS not the history of the DS team's template)"
What's the difference between a Design System and a Design System Template? Are there any Design System Template examples out there I can look at to better understand what it is?

**Comment by allthatyazz** [comment]
@sandraberjan for clarifications on the word "template" let's read the first bullet point from the notes above. 

> As the Design Systems team, our goal is to create a White Label version of the HfLA Website team's Design System that can serve as a template for other projects. If we consider our work as a product, let's call the product 'Universal Design Systems Template'. 

To go back to your question, 
> What's the difference between a Design System and a Design System Template?

In a practical sense, there is no difference between those two.  The DS team would create a design system as if it is meant for a hypothetical product so that other teams at HfLA would use our file as their template in the creation of their very own design system. So it is like we are creating the role model or the **mother version** of a design system that is somehow general enough and flexible enough that other teams can modify it and make their own **child version**.

**Comment by sandraberjan** [comment]
Thank you for responding, @allthatyazz ! I'm looking into what "White Label" means and found some examples of a "white label" design system. I think you are probably right about dropping the word "template". I'll research a tiny bit more on what people are calling similar systems like this (will spend less than 20 min on that) and report back on what I find.

> @sandraberjan for clarifications on the word "template" let's read the first bullet point from the notes above.
> 
> > As the Design Systems team, our goal is to create a White Label version of the HfLA Website team's Design System that can serve as a template for other projects. If we consider our work as a product, let's call the product 'Universal Design Systems Template'.
> 
> To go back to your question,
> 
> > What's the difference between a Design System and a Design System Template?
> 
> In a practical sense, there is no difference between those two. The DS team would create a design system as if it is meant for a hypothetical product so that other teams at HfLA would use our file as their template in the creation of their very own design system. So it is like we are creating the role model or the **mother version** of a design system that is somehow general enough and flexible enough that other teams can modify it and make their own **child version**.
> 
> My reflection after reading your comment is maybe we need to drop the word "template" from our product's name. Calling our product "HfLA's Universal Design Systems" for me is clear enough.

**Comment by ExperimentsInHonesty** [comment]
@allthatyazz for our next meeting
- https://github.com/hackforla/website/issues/3731#issuecomment-1445256946

**Comment by allthatyazz** [comment]
#3/6 

- [ ] Update the product 1 sheet on the website with Bonnie's help
- [ ] Review PRD for the Universal Design Systems
- [ ] Update on the team's progress

### Notes

**Comment by allthatyazz** [comment]
# 3/20
- Attendees: Bonnie (stakeholder), Josh (PM), Khanh (Design Lead)
- The button component was discussed during this meeting. 
- Khanh documented her takeaways in https://github.com/hackforla/design-systems/issues/487#issuecomment-1480429626

> **Khanh’s Update from the meeting with Bonnie**
> - Rather than a “Universal Design System Template” that can be adapted by all the teams currently under HfLA, Bonnie wanted something more along the lines of a “HfLA Design System Starter”
>      - Meaning that she wants a whole design system that can be copied and pasted for any new projects that has components already built out with code that other teams can just tweak
> - For the component list, we’ll look at the “Materials UI” to help us decide what to build out
> - From “Khanh’s Template Update (3/17/2023)” Bonnie would like us to add:
>      - “Base published date”
>      - We need to make the descriptive details component accurate
>      - Any repetitive details will just live in the same box

**Comment by allthatyazz** [comment]
# 5/1 
Attendees: Stakeholer, PMs @joshfishman @allthatyazz , Design Lead @khanhcao17, Content Lead @michyeh 

- [x] hackforla/UI-UX#487 Khanh to show [the latest stage of the components](https://www.figma.com/file/5NacfOm45QlrWgr6wWEg4k/Design-Systems-Team-Figma?node-id=2%3A59&t=pwQNL1oLRaTeYbCJ-1) to Bonnie. 
  - [x] Buttons 
  - [x] Menu
  - [x] Colors
  - [x] Typography
  - [x] Select ( WIP)
  - [x] Text Field (WIP)
- [ ] Michelle to give a brief overview of why we need to rethink the names, the name-storming activity, and the top contenders.
  - [x] hackforla/UI-UX#510
  - [x] hackforla/UI-UX#509 Hack for LA Figma Compass for the Figma guide ( cover page, start page etc.) 
 
# Notes 

- Bonnie brought up some branding issues related to the name "Compass" and the availability of the domain name for Figma Compass. However, it was suggested that a standalone domain might not be necessary.
- For now, Bonnie approved the name "HfLA Figma Compass," with the option to rebrand in the future if needed.
- Bonnie looked at different options for the design system template. She likes both UI basics and Design system Builder. However, the latter can convey an automated process. She had no problem with the use of the word "template" and she used the analogy of an "effective pattern book" that someone can use as is or decide to modify it. 
- The idea of conducting a survey on usability Hub to determine the best name for the component systems was discussed, but the content team advised against it.
- There was a discussion about the meaning of the "publish date" for the component template, and Bonnie suggested considering how other projects will use the dates.
- To meet the deadline, Bonnie recommended assigning designers with less experience to work on lower-priority components, and Khanh will manage this task.
